# Generated by Django 4.1.6 on 2023-02-14 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0002_alter_brands_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'managed': True, 'verbose_name': 'Brand'},
        ),
    ]
