# Generated by Django 4.1.6 on 2023-02-14 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0003_alter_brands_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'managed': True, 'verbose_name': 'Car'},
        ),
    ]
