# Generated by Django 4.1.6 on 2023-02-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0006_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='serviceList',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
