# Generated by Django 4.1.6 on 2023-02-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0007_orders_servicelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='serviceList',
            field=models.JSONField(),
        ),
    ]
