# Generated by Django 4.1.6 on 2023-02-22 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0008_alter_orders_servicelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='email',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid email format', regex='\\S{3,}\\@\\S{2,}\\.\\S{2,}')]),
        ),
    ]
